name: Deploy to Vercel (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: Deploy to Vercel (Production)
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
