name: Deploy to Vercel

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - run: npm run build

      - name: Deploy to Vercel (Preview)
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: team_3tYETRkCv0OTI7Akkx5QVZLl
          VERCEL_ENV: preview
