name: Deploy to Vercel

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm --scope olgavakulenko
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ENV: ${{ github.ref == 'refs/heads/staging' && 'preview' || 'preview-glow' }}
