name: Validate Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR is from staging
      run: |
        if [ "${{ github.head_ref }}" != "staging" ]; then
          echo "Pull request is not from staging. Failing the check."
          exit 1
        fi
      shell: bash
